[package]
name = "poe-layouts-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
poe-ggpk = { path = "../poe-ggpk" }
poe-schema = { path = "../poe-schema" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
