[package]
name = "poe-ggpk"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
blake3.workspace = true
reqwest = { workspace = true, default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta = { version = "1.44.1", features = ["yaml"] }
pretty_assertions = "1.4.1"

[lints]
workspace = true
