[package]
name = "poe-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "poe"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap = { workspace = true, features = ["derive"] }
poe-ggpk = { path = "../poe-ggpk" }
reqwest = { workspace = true, default-features = false, features = ["blocking", "rustls-tls"] }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
